spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 20011121
    url: jdbc:mysql://8.134.139.152:33066/evaluate?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowMultiQueries=true
mybatis:
  mapper-locations: classpath:Mapper/*.xml
server:
  port: 8080
