spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 20011121
    url: jdbc:mysql://8.134.139.152:33066/evaluate?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 配置扫描
  servlet:
    multipart:
      enabled: true
      max-request-size: 500MB
      max-file-size: 100MB
  redis:
    host: localhost
    port: 6379
  mvc:
    hiddenmethod:
      filter:
        #        开启put和delete请求
        enabled: true
  #        开启aop
  aop:
    auto: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8080
  tomcat:
    max-swallow-size: -1
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

# 配置文件
file:
  temp-pre-path: /root/upload/temp
  #  temp-pre-path: /Users/apple/Documents/Program/Java/EvaluateSystem/src/main/resources/static
  #  temp-pre-path: D:/levi/EvaluateSystem/src/main/resources/static
  #  temp-pre-path: G:/Programing/Java/Evaluate/src/main/resources/upload
  character-set: utf-8
  # 分片文件大小 10 * 1024 * 1024 * 1024 bit 即 4000MB
  file-size-max: 10737418240
  #  请求的最大大小 4000 * 1024 * 1024 * 1024 bit 即 4000MB
  request-size-max: 4294967296000
  # 文件缓冲区大小 1024MB
  threshold-size: 1024
  # 共享文件文件架
  share-pre-path: /root/upload/share
