spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 20011121
    url: jdbc:mysql://8.134.139.152:33066/evaluate?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    # 配置扫描
  servlet:
    multipart:
      enabled: false
  redis:
    host: localhost
    port: 6379
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8080
  tomcat:
    max-swallow-size: -1


# 配置文件
file:
  #  pre-path: /Users/apple/Library/CloudStorage/OneDrive-个人/Program/Java/EvaluateSystem/src/main/resources/static/upload
  pre-path: /root/upload
  character-set: utf-8
  # 分片文件大小 5 * 1024 * 1024 * 1024 bit 即 5MB
  file-size-max: 5368709120
  #  请求的最大大小 10 * 1024 * 1024 * 1024 bit 即 10M
  request-size-max: 1073741824
  # 文件缓冲区大小 1024MB
  threshold-size: 1024

